"""phase1d tenant status seats owner subscription seats

Revision ID: b879cb709462
Revises: ca8f070d09de
Create Date: 2026-08-22 00:37:12.031563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b879cb709462'
down_revision: Union[str, None] = 'ca8f070d09de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('seats', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('tenants', sa.Column('status', sa.String(), nullable=False, server_default='active'))
    op.add_column('tenants', sa.Column('seats_allocated', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('tenants', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tenants_owner_id_users', 'tenants', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tenants_owner_id_users', 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'owner_id')
    op.drop_column('tenants', 'seats_allocated')
    op.drop_column('tenants', 'status')
    op.drop_column('subscriptions', 'seats')
    # ### end Alembic commands ###
